version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rhinoda_app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PATH_CONF}/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ${PATH_CONF}/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${PATH_BACK}:/www
      - phpsocket:/var/run
    networks:
      - rhinoda-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_BACK}:/www
      - ${PATH_LOG}/nginx:/var/log/nginx/
      - ${PATH_CONF}/nginx/conf.d/${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - "phpsocket:/var/run"      
    networks:
      - rhinoda-network

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    working_dir: /www
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PATH_DB}/dump:/app/dump
      - ${PATH_DB}/db:/var/lib/postgresql/data
    networks:
      - rhinoda-network

#Docker Networks
networks:
  rhinoda-network:
    driver: bridge

volumes:
    phpsocket: